name: Update OpenAPI Spec

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "openapi/spec.json"
      - "openapi/**"

permissions:
  contents: write

jobs:
  update-openapi:
    runs-on: ubuntu-latestgit

    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Update submodule to latest remote commit
        run: |
          git submodule update --init --recursive
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cd openapi
          git fetch origin
          git checkout master
          git pull origin master
      - name: Generate spec.json
        run: |
          npm ci
          npm run generate:openapi

      - name: Commit changes
        run: |
          cd openapi



          git add spec.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update OpenAPI spec"
      - name: Push changes
        run: |
          cd openapi
          git status
          git branch
          git push origin master

      - name: Update parent repo submodule pointer
        run: |
          git submodule update --remote openapi
          git add openapi

          git diff --cached --quiet && echo "No submodule update" && exit 0

          git commit -m "chore: Update OpenAPI submodule"
          git push
